const countryCodes = {
  AF: { name: 'Afghanistan', flag: '/flags/af.svg' },
  AL: { name: 'Albania', flag: '/flags/al.svg' },
  DZ: { name: 'Algeria', flag: '/flags/dz.svg' },
  AS: { name: 'American Samoa', flag: '/flags/as.svg' },
  AD: { name: 'Andorra', flag: '/flags/ad.svg' },
  AO: { name: 'Angola', flag: '/flags/ao.svg' },
  AI: { name: 'Anguilla', flag: '/flags/ai.svg' },
  AQ: { name: 'Antarctica', flag: '/flags/aq.svg' },
  AG: { name: 'Antigua and Barbuda', flag: '/flags/ag.svg' },
  AR: { name: 'Argentina', flag: '/flags/ar.svg' },
  AM: { name: 'Armenia', flag: '/flags/am.svg' },
  AW: { name: 'Aruba', flag: '/flags/aw.svg' },
  AU: { name: 'Australia', flag: '/flags/au.svg' },
  AT: { name: 'Austria', flag: '/flags/at.svg' },
  AZ: { name: 'Azerbaijan', flag: '/flags/az.svg' },
  BS: { name: 'Bahamas', flag: '/flags/bs.svg' },
  BH: { name: 'Bahrain', flag: '/flags/bh.svg' },
  BD: { name: 'Bangladesh', flag: '/flags/bd.svg' },
  BB: { name: 'Barbados', flag: '/flags/bb.svg' },
  BY: { name: 'Belarus', flag: '/flags/by.svg' },
  BE: { name: 'Belgium', flag: '/flags/be.svg' },
  BZ: { name: 'Belize', flag: '/flags/bz.svg' },
  BJ: { name: 'Benin', flag: '/flags/bj.svg' },
  BM: { name: 'Bermuda', flag: '/flags/bm.svg' },
  BT: { name: 'Bhutan', flag: '/flags/bt.svg' },
  BO: { name: 'Bolivia', flag: '/flags/bo.svg' },
  BQ: { name: 'Bonaire, Sint Eustatius and Saba', flag: '/flags/bq.svg' },
  BA: { name: 'Bosnia and Herzegovina', flag: '/flags/ba.svg' },
  BW: { name: 'Botswana', flag: '/flags/bw.svg' },
  BV: { name: 'Bouvet Island', flag: '/flags/bv.svg' },
  BR: { name: 'Brazil', flag: '/flags/br.svg' },
  IO: { name: 'British Indian Ocean Territory', flag: '/flags/io.svg' },
  BN: { name: 'Brunei Darussalam', flag: '/flags/bn.svg' },
  BG: { name: 'Bulgaria', flag: '/flags/bg.svg' },
  BF: { name: 'Burkina Faso', flag: '/flags/bf.svg' },
  BI: { name: 'Burundi', flag: '/flags/bi.svg' },
  CV: { name: 'Cabo Verde', flag: '/flags/cv.svg' },
  KH: { name: 'Cambodia', flag: '/flags/kh.svg' },
  CM: { name: 'Cameroon', flag: '/flags/cm.svg' },
  CA: { name: 'Canada', flag: '/flags/ca.svg' },
  KY: { name: 'Cayman Islands', flag: '/flags/ky.svg' },
  CF: { name: 'Central African Republic', flag: '/flags/cf.svg' },
  TD: { name: 'Chad', flag: '/flags/td.svg' },
  CL: { name: 'Chile', flag: '/flags/cl.svg' },
  CN: { name: 'China', flag: '/flags/cn.svg' },
  CX: { name: 'Christmas Island', flag: '/flags/cx.svg' },
  CC: { name: 'Cocos (Keeling) Islands', flag: '/flags/cc.svg' },
  CO: { name: 'Colombia', flag: '/flags/co.svg' },
  KM: { name: 'Comoros', flag: '/flags/km.svg' },
  CD: { name: 'Democratic Republic of the Congo', flag: '/flags/cd.svg' },
  CG: { name: 'Congo', flag: '/flags/cg.svg' },
  CK: { name: 'Cook Islands', flag: '/flags/ck.svg' },
  CR: { name: 'Costa Rica', flag: '/flags/cr.svg' },
  HR: { name: 'Croatia', flag: '/flags/hr.svg' },
  CU: { name: 'Cuba', flag: '/flags/cu.svg' },
  CW: { name: 'Curaçao', flag: '/flags/cw.svg' },
  CY: { name: 'Cyprus', flag: '/flags/cy.svg' },
  CZ: { name: 'Czechia', flag: '/flags/cz.svg' },
  CI: { name: 'Côte d\'Ivoire', flag: '/flags/ci.svg' },
  DK: { name: 'Denmark', flag: '/flags/dk.svg' },
  DJ: { name: 'Djibouti', flag: '/flags/dj.svg' },
  DM: { name: 'Dominica', flag: '/flags/dm.svg' },
  DO: { name: 'Dominican Republic', flag: '/flags/do.svg' },
  EC: { name: 'Ecuador', flag: '/flags/ec.svg' },
  EG: { name: 'Egypt', flag: '/flags/eg.svg' },
  SV: { name: 'El Salvador', flag: '/flags/sv.svg' },
  GQ: { name: 'Equatorial Guinea', flag: '/flags/gq.svg' },
  ER: { name: 'Eritrea', flag: '/flags/er.svg' },
  EE: { name: 'Estonia', flag: '/flags/ee.svg' },
  SZ: { name: 'Eswatini', flag: '/flags/sz.svg' },
  ET: { name: 'Ethiopia', flag: '/flags/et.svg' },
  FK: { name: 'Falkland Islands [Malvinas]', flag: '/flags/fk.svg' },
  FO: { name: 'Faroe Islands', flag: '/flags/fo.svg' },
  FJ: { name: 'Fiji', flag: '/flags/fj.svg' },
  FI: { name: 'Finland', flag: '/flags/fi.svg' },
  FR: { name: 'France', flag: '/flags/fr.svg' },
  GF: { name: 'French Guiana', flag: '/flags/gf.svg' },
  PF: { name: 'French Polynesia', flag: '/flags/pf.svg' },
  TF: { name: 'French Southern Territories', flag: '/flags/tf.svg' },
  GA: { name: 'Gabon', flag: '/flags/ga.svg' },
  GM: { name: 'Gambia', flag: '/flags/gm.svg' },
  GE: { name: 'Georgia', flag: '/flags/ge.svg' },
  DE: { name: 'Germany', flag: '/flags/de.svg' },
  GH: { name: 'Ghana', flag: '/flags/gh.svg' },
  GI: { name: 'Gibraltar', flag: '/flags/gi.svg' },
  GR: { name: 'Greece', flag: '/flags/gr.svg' },
  GL: { name: 'Greenland', flag: '/flags/gl.svg' },
  GD: { name: 'Grenada', flag: '/flags/gd.svg' },
  GP: { name: 'Guadeloupe', flag: '/flags/gp.svg' },
  GU: { name: 'Guam', flag: '/flags/gu.svg' },
  GT: { name: 'Guatemala', flag: '/flags/gt.svg' },
  GG: { name: 'Guernsey', flag: '/flags/gg.svg' },
  GN: { name: 'Guinea', flag: '/flags/gn.svg' },
  GW: { name: 'Guinea-Bissau', flag: '/flags/gw.svg' },
  GY: { name: 'Guyana', flag: '/flags/gy.svg' },
  HT: { name: 'Haiti', flag: '/flags/ht.svg' },
  HM: { name: 'Heard Island and McDonald Islands', flag: '/flags/hm.svg' },
  VA: { name: 'Holy See', flag: '/flags/va.svg' },
  HN: { name: 'Honduras', flag: '/flags/hn.svg' },
  HK: { name: 'Hong Kong', flag: '/flags/hk.svg' },
  HU: { name: 'Hungary', flag: '/flags/hu.svg' },
  IS: { name: 'Iceland', flag: '/flags/is.svg' },
  IN: { name: 'India', flag: '/flags/in.svg' },
  ID: { name: 'Indonesia', flag: '/flags/id.svg' },
  IR: { name: 'Iran', flag: '/flags/ir.svg' },
  IQ: { name: 'Iraq', flag: '/flags/iq.svg' },
  IE: { name: 'Ireland', flag: '/flags/ie.svg' },
  IM: { name: 'Isle of Man', flag: '/flags/im.svg' },
  IL: { name: 'Israel', flag: '/flags/il.svg' },
  IT: { name: 'Italy', flag: '/flags/it.svg' },
  JM: { name: 'Jamaica', flag: '/flags/jm.svg' },
  JP: { name: 'Japan', flag: '/flags/jp.svg' },
  JE: { name: 'Jersey', flag: '/flags/je.svg' },
  JO: { name: 'Jordan', flag: '/flags/jo.svg' },
  KZ: { name: 'Kazakhstan', flag: '/flags/kz.svg' },
  KE: { name: 'Kenya', flag: '/flags/ke.svg' },
  KI: { name: 'Kiribati', flag: '/flags/ki.svg' },
  KP: { name: 'Democratic People\'s Republic of Korea', flag: '/flags/kp.svg' },
  KR: { name: 'Republic of Korea', flag: '/flags/kr.svg' },
  KW: { name: 'Kuwait', flag: '/flags/kw.svg' },
  KG: { name: 'Kyrgyzstan', flag: '/flags/kg.svg' },
  LA: { name: 'Lao People\'s Democratic Republic', flag: '/flags/la.svg' },
  LV: { name: 'Latvia', flag: '/flags/lv.svg' },
  LB: { name: 'Lebanon', flag: '/flags/lb.svg' },
  LS: { name: 'Lesotho', flag: '/flags/ls.svg' },
  LR: { name: 'Liberia', flag: '/flags/lr.svg' },
  LY: { name: 'Libya', flag: '/flags/ly.svg' },
  LI: { name: 'Liechtenstein', flag: '/flags/li.svg' },
  LT: { name: 'Lithuania', flag: '/flags/lt.svg' },
  LU: { name: 'Luxembourg', flag: '/flags/lu.svg' },
  MO: { name: 'Macao', flag: '/flags/mo.svg' },
  MG: { name: 'Madagascar', flag: '/flags/mg.svg' },
  MW: { name: 'Malawi', flag: '/flags/mw.svg' },
  MY: { name: 'Malaysia', flag: '/flags/my.svg' },
  MV: { name: 'Maldives', flag: '/flags/mv.svg' },
  ML: { name: 'Mali', flag: '/flags/ml.svg' },
  MT: { name: 'Malta', flag: '/flags/mt.svg' },
  MH: { name: 'Marshall Islands', flag: '/flags/mh.svg' },
  MQ: { name: 'Martinique', flag: '/flags/mq.svg' },
  MR: { name: 'Mauritania', flag: '/flags/mr.svg' },
  MU: { name: 'Mauritius', flag: '/flags/mu.svg' },
  YT: { name: 'Mayotte', flag: '/flags/yt.svg' },
  MX: { name: 'Mexico', flag: '/flags/mx.svg' },
  FM: { name: 'Micronesia', flag: '/flags/fm.svg' },
  MD: { name: 'Moldova', flag: '/flags/md.svg' },
  MC: { name: 'Monaco', flag: '/flags/mc.svg' },
  MN: { name: 'Mongolia', flag: '/flags/mn.svg' },
  ME: { name: 'Montenegro', flag: '/flags/me.svg' },
  MS: { name: 'Montserrat', flag: '/flags/ms.svg' },
  MA: { name: 'Morocco', flag: '/flags/ma.svg' },
  MZ: { name: 'Mozambique', flag: '/flags/mz.svg' },
  MM: { name: 'Myanmar', flag: '/flags/mm.svg' },
  NA: { name: 'Namibia', flag: '/flags/na.svg' },
  NR: { name: 'Nauru', flag: '/flags/nr.svg' },
  NP: { name: 'Nepal', flag: '/flags/np.svg' },
  NL: { name: 'Netherlands', flag: '/flags/nl.svg' },
  NC: { name: 'New Caledonia', flag: '/flags/nc.svg' },
  NZ: { name: 'New Zealand', flag: '/flags/nz.svg' },
  NI: { name: 'Nicaragua', flag: '/flags/ni.svg' },
  NE: { name: 'Niger', flag: '/flags/ne.svg' },
  NG: { name: 'Nigeria', flag: '/flags/ng.svg' },
  NU: { name: 'Niue', flag: '/flags/nu.svg' },
  NF: { name: 'Norfolk Island', flag: '/flags/nf.svg' },
  MP: { name: 'Northern Mariana Islands', flag: '/flags/mp.svg' },
  NO: { name: 'Norway', flag: '/flags/no.svg' },
  OM: { name: 'Oman', flag: '/flags/om.svg' },
  PK: { name: 'Pakistan', flag: '/flags/pk.svg' },
  PW: { name: 'Palau', flag: '/flags/pw.svg' },
  PS: { name: 'Palestine', flag: '/flags/ps.svg' },
  PA: { name: 'Panama', flag: '/flags/pa.svg' },
  PG: { name: 'Papua New Guinea', flag: '/flags/pg.svg' },
  PY: { name: 'Paraguay', flag: '/flags/py.svg' },
  PE: { name: 'Peru', flag: '/flags/pe.svg' },
  PH: { name: 'Philippines', flag: '/flags/ph.svg' },
  PN: { name: 'Pitcairn', flag: '/flags/pn.svg' },
  PL: { name: 'Poland', flag: '/flags/pl.svg' },
  PT: { name: 'Portugal', flag: '/flags/pt.svg' },
  PR: { name: 'Puerto Rico', flag: '/flags/pr.svg' },
  QA: { name: 'Qatar', flag: '/flags/qa.svg' },
  MK: { name: 'North Macedonia', flag: '/flags/mk.svg' },
  RO: { name: 'Romania', flag: '/flags/ro.svg' },
  RU: { name: 'Russian Federation', flag: '/flags/ru.svg' },
  RW: { name: 'Rwanda', flag: '/flags/rw.svg' },
  RE: { name: 'Réunion', flag: '/flags/re.svg' },
  BL: { name: 'Saint Barthélemy', flag: '/flags/bl.svg' },
  SH: { name: 'Saint Helena, Ascension and Tristan da Cunha', flag: '/flags/sh.svg' },
  KN: { name: 'Saint Kitts and Nevis', flag: '/flags/kn.svg' },
  LC: { name: 'Saint Lucia', flag: '/flags/lc.svg' },
  MF: { name: 'Saint Martin (French part)', flag: '/flags/mf.svg' },
  PM: { name: 'Saint Pierre and Miquelon', flag: '/flags/pm.svg' },
  VC: { name: 'Saint Vincent and the Grenadines', flag: '/flags/vc.svg' },
  WS: { name: 'Samoa', flag: '/flags/ws.svg' },
  SM: { name: 'San Marino', flag: '/flags/sm.svg' },
  ST: { name: 'Sao Tome and Principe', flag: '/flags/st.svg' },
  SA: { name: 'Saudi Arabia', flag: '/flags/sa.svg' },
  SN: { name: 'Senegal', flag: '/flags/sn.svg' },
  RS: { name: 'Serbia', flag: '/flags/rs.svg' },
  SC: { name: 'Seychelles', flag: '/flags/sc.svg' },
  SL: { name: 'Sierra Leone', flag: '/flags/sl.svg' },
  SG: { name: 'Singapore', flag: '/flags/sg.svg' },
  SX: { name: 'Sint Maarten (Dutch part)', flag: '/flags/sx.svg' },
  SK: { name: 'Slovakia', flag: '/flags/sk.svg' },
  SI: { name: 'Slovenia', flag: '/flags/si.svg' },
  SB: { name: 'Solomon Islands', flag: '/flags/sb.svg' },
  SO: { name: 'Somalia', flag: '/flags/so.svg' },
  ZA: { name: 'South Africa', flag: '/flags/za.svg' },
  GS: { name: 'South Georgia and the South Sandwich Islands', flag: '/flags/gs.svg' },
  SS: { name: 'South Sudan', flag: '/flags/ss.svg' },
  ES: { name: 'Spain', flag: '/flags/es.svg' },
  LK: { name: 'Sri Lanka', flag: '/flags/lk.svg' },
  SD: { name: 'Sudan', flag: '/flags/sd.svg' },
  SR: { name: 'Suriname', flag: '/flags/sr.svg' },
  SJ: { name: 'Svalbard and Jan Mayen', flag: '/flags/sj.svg' },
  SE: { name: 'Sweden', flag: '/flags/se.svg' },
  CH: { name: 'Switzerland', flag: '/flags/ch.svg' },
  SY: { name: 'Syrian Arab Republic', flag: '/flags/sy.svg' },
  TW: { name: 'Taiwan', flag: '/flags/tw.svg' },
  TJ: { name: 'Tajikistan', flag: '/flags/tj.svg' },
  TZ: { name: 'Tanzania', flag: '/flags/tz.svg' },
  TH: { name: 'Thailand', flag: '/flags/th.svg' },
  TL: { name: 'Timor-Leste', flag: '/flags/tl.svg' },
  TG: { name: 'Togo', flag: '/flags/tg.svg' },
  TK: { name: 'Tokelau', flag: '/flags/tk.svg' },
  TO: { name: 'Tonga', flag: '/flags/to.svg' },
  TT: { name: 'Trinidad and Tobago', flag: '/flags/tt.svg' },
  TN: { name: 'Tunisia', flag: '/flags/tn.svg' },
  TR: { name: 'Turkey', flag: '/flags/tr.svg' },
  TM: { name: 'Turkmenistan', flag: '/flags/tm.svg' },
  TC: { name: 'Turks and Caicos Islands', flag: '/flags/tc.svg' },
  TV: { name: 'Tuvalu', flag: '/flags/tv.svg' },
  UG: { name: 'Uganda', flag: '/flags/ug.svg' },
  UA: { name: 'Ukraine', flag: '/flags/ua.svg' },
  AE: { name: 'United Arab Emirates', flag: '/flags/ae.svg' },
  GB: { name: 'United Kingdom', flag: '/flags/gb.svg' },
  UM: { name: 'United States Minor Outlying Islands', flag: '/flags/um.svg' },
  US: { name: 'United States', flag: '/flags/us.svg' },
  UY: { name: 'Uruguay', flag: '/flags/uy.svg' },
  UZ: { name: 'Uzbekistan', flag: '/flags/uz.svg' },
  VU: { name: 'Vanuatu', flag: '/flags/vu.svg' },
  VE: { name: 'Venezuela', flag: '/flags/ve.svg' },
  VN: { name: 'Viet Nam', flag: '/flags/vn.svg' },
  VG: { name: 'Virgin Islands (British)', flag: '/flags/vg.svg' },
  VI: { name: 'Virgin Islands (U.S.)', flag: '/flags/vi.svg' },
  WF: { name: 'Wallis and Futuna', flag: '/flags/wf.svg' },
  EH: { name: 'Western Sahara', flag: '/flags/eh.svg' },
  YE: { name: 'Yemen', flag: '/flags/ye.svg' },
  ZM: { name: 'Zambia', flag: '/flags/zm.svg' },
  ZW: { name: 'Zimbabwe', flag: '/flags/zw.svg' },
  AX: { name: 'Åland Islands', flag: '/flags/ax.svg' },
};

const getCountry = (code) => {
  return countryCodes[code.toUpperCase()];
}

const getCountryName = (code) => {
  return countryCodes[code.toUpperCase()].name;
}

const getLanguageData = (lang) => {
  const cLang = Intl.getCanonicalLocales(lang)[0];
  const name = new Intl.DisplayNames([cLang], {type: 'language'});

  const langObj = {};
  langObj.langDesc = name.of(cLang);
  langObj.locale = cLang;
  langObj.flag = countryCodes[cLang.slice(-2).toUpperCase()].flag;

  return langObj;
}

export { getCountry, getCountryName, getLanguageData };